// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PM struct {
	PMName               string   `protobuf:"bytes,1,opt,name=PMName,proto3" json:"PMName,omitempty"`
	Vcpu                 uint32   `protobuf:"varint,2,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	Memory               uint32   `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Ipaddress            string   `protobuf:"bytes,4,opt,name=ipaddress,proto3" json:"ipaddress,omitempty"`
	Storage              uint32   `protobuf:"varint,5,opt,name=storage,proto3" json:"storage,omitempty"`
	Username             string   `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	State                bool     `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PM) Reset()         { *m = PM{} }
func (m *PM) String() string { return proto.CompactTextString(m) }
func (*PM) ProtoMessage()    {}
func (*PM) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *PM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PM.Unmarshal(m, b)
}
func (m *PM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PM.Marshal(b, m, deterministic)
}
func (m *PM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PM.Merge(m, src)
}
func (m *PM) XXX_Size() int {
	return xxx_messageInfo_PM.Size(m)
}
func (m *PM) XXX_DiscardUnknown() {
	xxx_messageInfo_PM.DiscardUnknown(m)
}

var xxx_messageInfo_PM proto.InternalMessageInfo

func (m *PM) GetPMName() string {
	if m != nil {
		return m.PMName
	}
	return ""
}

func (m *PM) GetVcpu() uint32 {
	if m != nil {
		return m.Vcpu
	}
	return 0
}

func (m *PM) GetMemory() uint32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *PM) GetIpaddress() string {
	if m != nil {
		return m.Ipaddress
	}
	return ""
}

func (m *PM) GetStorage() uint32 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *PM) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PM) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PM) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

type VMONPM struct {
	VMId                 []string `protobuf:"bytes,1,rep,name=VMId,proto3" json:"VMId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VMONPM) Reset()         { *m = VMONPM{} }
func (m *VMONPM) String() string { return proto.CompactTextString(m) }
func (*VMONPM) ProtoMessage()    {}
func (*VMONPM) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *VMONPM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VMONPM.Unmarshal(m, b)
}
func (m *VMONPM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VMONPM.Marshal(b, m, deterministic)
}
func (m *VMONPM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VMONPM.Merge(m, src)
}
func (m *VMONPM) XXX_Size() int {
	return xxx_messageInfo_VMONPM.Size(m)
}
func (m *VMONPM) XXX_DiscardUnknown() {
	xxx_messageInfo_VMONPM.DiscardUnknown(m)
}

var xxx_messageInfo_VMONPM proto.InternalMessageInfo

func (m *VMONPM) GetVMId() []string {
	if m != nil {
		return m.VMId
	}
	return nil
}

type MigratingToPM struct {
	VMId                 []string `protobuf:"bytes,1,rep,name=VMId,proto3" json:"VMId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigratingToPM) Reset()         { *m = MigratingToPM{} }
func (m *MigratingToPM) String() string { return proto.CompactTextString(m) }
func (*MigratingToPM) ProtoMessage()    {}
func (*MigratingToPM) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *MigratingToPM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigratingToPM.Unmarshal(m, b)
}
func (m *MigratingToPM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigratingToPM.Marshal(b, m, deterministic)
}
func (m *MigratingToPM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigratingToPM.Merge(m, src)
}
func (m *MigratingToPM) XXX_Size() int {
	return xxx_messageInfo_MigratingToPM.Size(m)
}
func (m *MigratingToPM) XXX_DiscardUnknown() {
	xxx_messageInfo_MigratingToPM.DiscardUnknown(m)
}

var xxx_messageInfo_MigratingToPM proto.InternalMessageInfo

func (m *MigratingToPM) GetVMId() []string {
	if m != nil {
		return m.VMId
	}
	return nil
}

type FailedPM struct {
	PMId                 []string `protobuf:"bytes,1,rep,name=PMId,proto3" json:"PMId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailedPM) Reset()         { *m = FailedPM{} }
func (m *FailedPM) String() string { return proto.CompactTextString(m) }
func (*FailedPM) ProtoMessage()    {}
func (*FailedPM) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *FailedPM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailedPM.Unmarshal(m, b)
}
func (m *FailedPM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailedPM.Marshal(b, m, deterministic)
}
func (m *FailedPM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailedPM.Merge(m, src)
}
func (m *FailedPM) XXX_Size() int {
	return xxx_messageInfo_FailedPM.Size(m)
}
func (m *FailedPM) XXX_DiscardUnknown() {
	xxx_messageInfo_FailedPM.DiscardUnknown(m)
}

var xxx_messageInfo_FailedPM proto.InternalMessageInfo

func (m *FailedPM) GetPMId() []string {
	if m != nil {
		return m.PMId
	}
	return nil
}

type Partition struct {
	Ipaddress            []string `protobuf:"bytes,1,rep,name=ipaddress,proto3" json:"ipaddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetIpaddress() []string {
	if m != nil {
		return m.Ipaddress
	}
	return nil
}

func init() {
	proto.RegisterType((*PM)(nil), "PM")
	proto.RegisterType((*VMONPM)(nil), "VMONPM")
	proto.RegisterType((*MigratingToPM)(nil), "MigratingToPM")
	proto.RegisterType((*FailedPM)(nil), "FailedPM")
	proto.RegisterType((*Partition)(nil), "Partition")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x49, 0x7f, 0xa6, 0x33, 0x57, 0xba, 0x09, 0x22, 0x17, 0x29, 0x32, 0x8c, 0x9b, 0x71,
	0xe3, 0xc6, 0x77, 0x10, 0x5c, 0xa4, 0x86, 0x41, 0xba, 0x8f, 0x26, 0x0c, 0x01, 0x67, 0x12, 0x92,
	0x5b, 0xa5, 0x2f, 0xe9, 0x33, 0x49, 0x32, 0xad, 0xd5, 0x85, 0xbb, 0xf3, 0x9d, 0x73, 0x6e, 0x7e,
	0x2e, 0x5c, 0xd0, 0xc1, 0x9b, 0x78, 0xef, 0x83, 0x23, 0xd7, 0x7c, 0x31, 0x98, 0x49, 0xc1, 0xaf,
	0xa0, 0x90, 0x62, 0xab, 0x06, 0x83, 0xac, 0x66, 0x6d, 0xd5, 0x1d, 0x89, 0x73, 0x58, 0x7c, 0xbc,
	0xf9, 0x3d, 0xce, 0x6a, 0xd6, 0xae, 0xbb, 0xac, 0x53, 0x77, 0x30, 0x83, 0x0b, 0x07, 0x9c, 0x67,
	0xf7, 0x48, 0x7c, 0x03, 0x95, 0xf5, 0x4a, 0xeb, 0x60, 0x62, 0xc4, 0x45, 0x3e, 0xe6, 0x6c, 0x70,
	0x84, 0x55, 0x24, 0x17, 0x54, 0x6f, 0x70, 0x99, 0xc7, 0x4e, 0xc8, 0xaf, 0xa1, 0xdc, 0x47, 0x13,
	0xc6, 0x74, 0x7b, 0x91, 0xc7, 0x7e, 0x38, 0x65, 0x5e, 0xc5, 0xf8, 0xe9, 0x82, 0xc6, 0xd5, 0x94,
	0x9d, 0x98, 0x5f, 0xc2, 0x32, 0x92, 0x22, 0x83, 0x65, 0xcd, 0xda, 0xb2, 0x9b, 0xa0, 0xd9, 0x40,
	0xb1, 0x13, 0xcf, 0x5b, 0x29, 0xd2, 0xdb, 0x77, 0xe2, 0x49, 0x23, 0xab, 0xe7, 0x6d, 0xd5, 0x65,
	0xdd, 0xdc, 0xc2, 0x5a, 0xd8, 0x3e, 0x28, 0xb2, 0x63, 0xff, 0xe2, 0xfe, 0x29, 0xdd, 0x40, 0xf9,
	0xa8, 0xec, 0xbb, 0xd1, 0x53, 0x2e, 0x7f, 0xe5, 0x49, 0x37, 0x77, 0x50, 0x49, 0x15, 0xc8, 0x92,
	0x75, 0xe3, 0xdf, 0x5f, 0x4f, 0xad, 0xb3, 0xf1, 0x5a, 0xe4, 0x2d, 0x3f, 0x7c, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x73, 0xe4, 0x75, 0x6d, 0x74, 0x01, 0x00, 0x00,
}
