# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import napolet_pb2 as napolet__pb2


class PingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateVM = channel.unary_unary(
        '/Ping/CreateVM',
        request_serializer=napolet__pb2.CreateVMRequest.SerializeToString,
        response_deserializer=napolet__pb2.CreateVMResponse.FromString,
        )
    self.DeleteVM = channel.unary_unary(
        '/Ping/DeleteVM',
        request_serializer=napolet__pb2.DeleteVMRequest.SerializeToString,
        response_deserializer=napolet__pb2.DeleteVMResponse.FromString,
        )
    self.GetStat = channel.unary_unary(
        '/Ping/GetStat',
        request_serializer=napolet__pb2.Dummy.SerializeToString,
        response_deserializer=napolet__pb2.Stat.FromString,
        )


class PingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateVM(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteVM(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateVM': grpc.unary_unary_rpc_method_handler(
          servicer.CreateVM,
          request_deserializer=napolet__pb2.CreateVMRequest.FromString,
          response_serializer=napolet__pb2.CreateVMResponse.SerializeToString,
      ),
      'DeleteVM': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteVM,
          request_deserializer=napolet__pb2.DeleteVMRequest.FromString,
          response_serializer=napolet__pb2.DeleteVMResponse.SerializeToString,
      ),
      'GetStat': grpc.unary_unary_rpc_method_handler(
          servicer.GetStat,
          request_deserializer=napolet__pb2.Dummy.FromString,
          response_serializer=napolet__pb2.Stat.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Ping', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
