// Code generated by protoc-gen-go. DO NOT EDIT.
// source: leader.proto

package leader

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PMInformation struct {
	PMId                 string   `protobuf:"bytes,1,opt,name=PMId,proto3" json:"PMId,omitempty"`
	CapacityCpu          uint32   `protobuf:"varint,2,opt,name=capacityCpu,proto3" json:"capacityCpu,omitempty"`
	CapacityMemory       uint32   `protobuf:"varint,3,opt,name=capacityMemory,proto3" json:"capacityMemory,omitempty"`
	SlackCpu             uint32   `protobuf:"varint,4,opt,name=slackCpu,proto3" json:"slackCpu,omitempty"`
	SlackMemory          uint32   `protobuf:"varint,5,opt,name=slackMemory,proto3" json:"slackMemory,omitempty"`
	Number               uint32   `protobuf:"varint,6,opt,name=number,proto3" json:"number,omitempty"`
	State                bool     `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PMInformation) Reset()         { *m = PMInformation{} }
func (m *PMInformation) String() string { return proto.CompactTextString(m) }
func (*PMInformation) ProtoMessage()    {}
func (*PMInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{0}
}

func (m *PMInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMInformation.Unmarshal(m, b)
}
func (m *PMInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMInformation.Marshal(b, m, deterministic)
}
func (m *PMInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMInformation.Merge(m, src)
}
func (m *PMInformation) XXX_Size() int {
	return xxx_messageInfo_PMInformation.Size(m)
}
func (m *PMInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PMInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PMInformation proto.InternalMessageInfo

func (m *PMInformation) GetPMId() string {
	if m != nil {
		return m.PMId
	}
	return ""
}

func (m *PMInformation) GetCapacityCpu() uint32 {
	if m != nil {
		return m.CapacityCpu
	}
	return 0
}

func (m *PMInformation) GetCapacityMemory() uint32 {
	if m != nil {
		return m.CapacityMemory
	}
	return 0
}

func (m *PMInformation) GetSlackCpu() uint32 {
	if m != nil {
		return m.SlackCpu
	}
	return 0
}

func (m *PMInformation) GetSlackMemory() uint32 {
	if m != nil {
		return m.SlackMemory
	}
	return 0
}

func (m *PMInformation) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *PMInformation) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

type CreateNewVMRequest struct {
	VMId                 string   `protobuf:"bytes,1,opt,name=VMId,proto3" json:"VMId,omitempty"`
	PMId                 string   `protobuf:"bytes,2,opt,name=PMId,proto3" json:"PMId,omitempty"`
	Pcpu                 uint32   `protobuf:"varint,3,opt,name=pcpu,proto3" json:"pcpu,omitempty"`
	Pmemory              uint32   `protobuf:"varint,4,opt,name=pmemory,proto3" json:"pmemory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewVMRequest) Reset()         { *m = CreateNewVMRequest{} }
func (m *CreateNewVMRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNewVMRequest) ProtoMessage()    {}
func (*CreateNewVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{1}
}

func (m *CreateNewVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewVMRequest.Unmarshal(m, b)
}
func (m *CreateNewVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewVMRequest.Marshal(b, m, deterministic)
}
func (m *CreateNewVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewVMRequest.Merge(m, src)
}
func (m *CreateNewVMRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNewVMRequest.Size(m)
}
func (m *CreateNewVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewVMRequest proto.InternalMessageInfo

func (m *CreateNewVMRequest) GetVMId() string {
	if m != nil {
		return m.VMId
	}
	return ""
}

func (m *CreateNewVMRequest) GetPMId() string {
	if m != nil {
		return m.PMId
	}
	return ""
}

func (m *CreateNewVMRequest) GetPcpu() uint32 {
	if m != nil {
		return m.Pcpu
	}
	return 0
}

func (m *CreateNewVMRequest) GetPmemory() uint32 {
	if m != nil {
		return m.Pmemory
	}
	return 0
}

type CreateNewVMResponse struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewVMResponse) Reset()         { *m = CreateNewVMResponse{} }
func (m *CreateNewVMResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNewVMResponse) ProtoMessage()    {}
func (*CreateNewVMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{2}
}

func (m *CreateNewVMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewVMResponse.Unmarshal(m, b)
}
func (m *CreateNewVMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewVMResponse.Marshal(b, m, deterministic)
}
func (m *CreateNewVMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewVMResponse.Merge(m, src)
}
func (m *CreateNewVMResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNewVMResponse.Size(m)
}
func (m *CreateNewVMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewVMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewVMResponse proto.InternalMessageInfo

func (m *CreateNewVMResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

type DeleteVMRequest struct {
	VMId                 string   `protobuf:"bytes,1,opt,name=VMId,proto3" json:"VMId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVMRequest) Reset()         { *m = DeleteVMRequest{} }
func (m *DeleteVMRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVMRequest) ProtoMessage()    {}
func (*DeleteVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{3}
}

func (m *DeleteVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVMRequest.Unmarshal(m, b)
}
func (m *DeleteVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVMRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVMRequest.Merge(m, src)
}
func (m *DeleteVMRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVMRequest.Size(m)
}
func (m *DeleteVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVMRequest proto.InternalMessageInfo

func (m *DeleteVMRequest) GetVMId() string {
	if m != nil {
		return m.VMId
	}
	return ""
}

type DeleteVMResponse struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVMResponse) Reset()         { *m = DeleteVMResponse{} }
func (m *DeleteVMResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVMResponse) ProtoMessage()    {}
func (*DeleteVMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{4}
}

func (m *DeleteVMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVMResponse.Unmarshal(m, b)
}
func (m *DeleteVMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVMResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVMResponse.Merge(m, src)
}
func (m *DeleteVMResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVMResponse.Size(m)
}
func (m *DeleteVMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVMResponse proto.InternalMessageInfo

func (m *DeleteVMResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

type StateRequest struct {
	NumOn                uint32   `protobuf:"varint,1,opt,name=numOn,proto3" json:"numOn,omitempty"`
	NumOff               uint32   `protobuf:"varint,2,opt,name=numOff,proto3" json:"numOff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateRequest) Reset()         { *m = StateRequest{} }
func (m *StateRequest) String() string { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()    {}
func (*StateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{5}
}

func (m *StateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateRequest.Unmarshal(m, b)
}
func (m *StateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateRequest.Marshal(b, m, deterministic)
}
func (m *StateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateRequest.Merge(m, src)
}
func (m *StateRequest) XXX_Size() int {
	return xxx_messageInfo_StateRequest.Size(m)
}
func (m *StateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StateRequest proto.InternalMessageInfo

func (m *StateRequest) GetNumOn() uint32 {
	if m != nil {
		return m.NumOn
	}
	return 0
}

func (m *StateRequest) GetNumOff() uint32 {
	if m != nil {
		return m.NumOff
	}
	return 0
}

type StateResponse struct {
	Pm                   []*PMInformation `protobuf:"bytes,1,rep,name=pm,proto3" json:"pm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StateResponse) Reset()         { *m = StateResponse{} }
func (m *StateResponse) String() string { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()    {}
func (*StateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{6}
}

func (m *StateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateResponse.Unmarshal(m, b)
}
func (m *StateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateResponse.Marshal(b, m, deterministic)
}
func (m *StateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateResponse.Merge(m, src)
}
func (m *StateResponse) XXX_Size() int {
	return xxx_messageInfo_StateResponse.Size(m)
}
func (m *StateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StateResponse proto.InternalMessageInfo

func (m *StateResponse) GetPm() []*PMInformation {
	if m != nil {
		return m.Pm
	}
	return nil
}

type StateUpdateRequest struct {
	PMId                 string   `protobuf:"bytes,1,opt,name=PMId,proto3" json:"PMId,omitempty"`
	SlackCpu             uint32   `protobuf:"varint,2,opt,name=slackCpu,proto3" json:"slackCpu,omitempty"`
	SlackMemory          uint32   `protobuf:"varint,3,opt,name=slackMemory,proto3" json:"slackMemory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateUpdateRequest) Reset()         { *m = StateUpdateRequest{} }
func (m *StateUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*StateUpdateRequest) ProtoMessage()    {}
func (*StateUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{7}
}

func (m *StateUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateUpdateRequest.Unmarshal(m, b)
}
func (m *StateUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateUpdateRequest.Marshal(b, m, deterministic)
}
func (m *StateUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateUpdateRequest.Merge(m, src)
}
func (m *StateUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_StateUpdateRequest.Size(m)
}
func (m *StateUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StateUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StateUpdateRequest proto.InternalMessageInfo

func (m *StateUpdateRequest) GetPMId() string {
	if m != nil {
		return m.PMId
	}
	return ""
}

func (m *StateUpdateRequest) GetSlackCpu() uint32 {
	if m != nil {
		return m.SlackCpu
	}
	return 0
}

func (m *StateUpdateRequest) GetSlackMemory() uint32 {
	if m != nil {
		return m.SlackMemory
	}
	return 0
}

type StateUpdateResponse struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateUpdateResponse) Reset()         { *m = StateUpdateResponse{} }
func (m *StateUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*StateUpdateResponse) ProtoMessage()    {}
func (*StateUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{8}
}

func (m *StateUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateUpdateResponse.Unmarshal(m, b)
}
func (m *StateUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateUpdateResponse.Marshal(b, m, deterministic)
}
func (m *StateUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateUpdateResponse.Merge(m, src)
}
func (m *StateUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_StateUpdateResponse.Size(m)
}
func (m *StateUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StateUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StateUpdateResponse proto.InternalMessageInfo

func (m *StateUpdateResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

type MigrateVMRequest struct {
	Assigned             []*CreateNewVMRequest `protobuf:"bytes,1,rep,name=assigned,proto3" json:"assigned,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MigrateVMRequest) Reset()         { *m = MigrateVMRequest{} }
func (m *MigrateVMRequest) String() string { return proto.CompactTextString(m) }
func (*MigrateVMRequest) ProtoMessage()    {}
func (*MigrateVMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{9}
}

func (m *MigrateVMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateVMRequest.Unmarshal(m, b)
}
func (m *MigrateVMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateVMRequest.Marshal(b, m, deterministic)
}
func (m *MigrateVMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateVMRequest.Merge(m, src)
}
func (m *MigrateVMRequest) XXX_Size() int {
	return xxx_messageInfo_MigrateVMRequest.Size(m)
}
func (m *MigrateVMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateVMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateVMRequest proto.InternalMessageInfo

func (m *MigrateVMRequest) GetAssigned() []*CreateNewVMRequest {
	if m != nil {
		return m.Assigned
	}
	return nil
}

type MigrateVMResponse struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateVMResponse) Reset()         { *m = MigrateVMResponse{} }
func (m *MigrateVMResponse) String() string { return proto.CompactTextString(m) }
func (*MigrateVMResponse) ProtoMessage()    {}
func (*MigrateVMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16c0f17a0047848a, []int{10}
}

func (m *MigrateVMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateVMResponse.Unmarshal(m, b)
}
func (m *MigrateVMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateVMResponse.Marshal(b, m, deterministic)
}
func (m *MigrateVMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateVMResponse.Merge(m, src)
}
func (m *MigrateVMResponse) XXX_Size() int {
	return xxx_messageInfo_MigrateVMResponse.Size(m)
}
func (m *MigrateVMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateVMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateVMResponse proto.InternalMessageInfo

func (m *MigrateVMResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func init() {
	proto.RegisterType((*PMInformation)(nil), "PMInformation")
	proto.RegisterType((*CreateNewVMRequest)(nil), "CreateNewVMRequest")
	proto.RegisterType((*CreateNewVMResponse)(nil), "CreateNewVMResponse")
	proto.RegisterType((*DeleteVMRequest)(nil), "DeleteVMRequest")
	proto.RegisterType((*DeleteVMResponse)(nil), "DeleteVMResponse")
	proto.RegisterType((*StateRequest)(nil), "StateRequest")
	proto.RegisterType((*StateResponse)(nil), "StateResponse")
	proto.RegisterType((*StateUpdateRequest)(nil), "StateUpdateRequest")
	proto.RegisterType((*StateUpdateResponse)(nil), "StateUpdateResponse")
	proto.RegisterType((*MigrateVMRequest)(nil), "MigrateVMRequest")
	proto.RegisterType((*MigrateVMResponse)(nil), "MigrateVMResponse")
}

func init() { proto.RegisterFile("leader.proto", fileDescriptor_16c0f17a0047848a) }

var fileDescriptor_16c0f17a0047848a = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xdd, 0x24, 0x4d, 0x27, 0x4d, 0x9a, 0x4c, 0x22, 0x64, 0xf9, 0x80, 0xac, 0x95, 0x40,
	0x39, 0x6d, 0xd4, 0x82, 0x84, 0x84, 0x10, 0x97, 0x70, 0xe9, 0xc1, 0xb4, 0x72, 0x45, 0xef, 0x5b,
	0x67, 0x12, 0x0c, 0xb1, 0xbd, 0xd8, 0x6b, 0x50, 0xff, 0x10, 0xff, 0x89, 0x7f, 0x83, 0xbc, 0x76,
	0xcc, 0xe6, 0x43, 0xa5, 0xb7, 0x79, 0x9b, 0xd9, 0x79, 0xfb, 0xde, 0x9b, 0x18, 0xce, 0x37, 0x24,
	0x96, 0x94, 0x71, 0x99, 0xa5, 0x2a, 0x65, 0x7f, 0x2c, 0x18, 0xdc, 0xfa, 0xd7, 0xc9, 0x2a, 0xcd,
	0x62, 0xa1, 0xa2, 0x34, 0x41, 0x84, 0xf6, 0xad, 0x7f, 0xbd, 0x74, 0x2c, 0xcf, 0x9a, 0x9d, 0x05,
	0xba, 0x46, 0x0f, 0xfa, 0xa1, 0x90, 0x22, 0x8c, 0xd4, 0xe3, 0x42, 0x16, 0x8e, 0xed, 0x59, 0xb3,
	0x41, 0x60, 0x1e, 0xe1, 0x6b, 0x18, 0x6e, 0xa1, 0x4f, 0x71, 0x9a, 0x3d, 0x3a, 0x27, 0xba, 0x69,
	0xef, 0x14, 0x5d, 0xe8, 0xe5, 0x1b, 0x11, 0x7e, 0x2f, 0xc7, 0xb4, 0x75, 0x47, 0x83, 0x4b, 0x16,
	0x5d, 0xd7, 0x03, 0x3a, 0x15, 0x8b, 0x71, 0x84, 0x2f, 0xa0, 0x9b, 0x14, 0xf1, 0x03, 0x65, 0x4e,
	0x57, 0xff, 0x58, 0x23, 0x9c, 0x42, 0x27, 0x57, 0x42, 0x91, 0x73, 0xea, 0x59, 0xb3, 0x5e, 0x50,
	0x01, 0xf6, 0x0d, 0x70, 0x91, 0x91, 0x50, 0xf4, 0x99, 0x7e, 0xdd, 0xfb, 0x01, 0xfd, 0x28, 0x28,
	0x57, 0xa5, 0xbe, 0x7b, 0x43, 0x5f, 0x59, 0x37, 0x9a, 0x6d, 0x43, 0x33, 0x42, 0x5b, 0x86, 0xb2,
	0xa8, 0x75, 0xe8, 0x1a, 0x1d, 0x38, 0x95, 0x71, 0xf5, 0xba, 0xea, 0xf1, 0x5b, 0xc8, 0x2e, 0x61,
	0xb2, 0xc3, 0x95, 0xcb, 0x34, 0xc9, 0xa9, 0x94, 0x2b, 0xc2, 0x90, 0xa4, 0xa2, 0x8a, 0xb0, 0x17,
	0x34, 0x98, 0xbd, 0x82, 0x8b, 0x4f, 0xb4, 0x21, 0x45, 0x4f, 0xbe, 0x8d, 0x71, 0x18, 0xfd, 0x6b,
	0x7b, 0xc6, 0xd8, 0x0f, 0x70, 0x7e, 0x57, 0xca, 0xdf, 0xce, 0x9c, 0x42, 0x27, 0x29, 0xe2, 0x9b,
	0x44, 0x37, 0x0e, 0x82, 0x0a, 0xd4, 0x4e, 0xde, 0xac, 0x56, 0x75, 0x98, 0x35, 0x62, 0x73, 0x18,
	0xd4, 0xb7, 0x6b, 0xaa, 0x97, 0x60, 0xcb, 0xd8, 0xb1, 0xbc, 0x93, 0x59, 0xff, 0x6a, 0xc8, 0x77,
	0x56, 0x25, 0xb0, 0x65, 0xcc, 0x56, 0x80, 0xfa, 0xc2, 0x17, 0xb9, 0x34, 0x48, 0x8f, 0x2d, 0x91,
	0x19, 0xbd, 0xfd, 0x74, 0xf4, 0x27, 0x07, 0xd1, 0x97, 0x06, 0xef, 0xf0, 0x3c, 0xc3, 0x89, 0x05,
	0x8c, 0xfc, 0x68, 0x9d, 0x09, 0xd3, 0xe1, 0x39, 0xf4, 0x44, 0x9e, 0x47, 0xeb, 0x44, 0xf7, 0x97,
	0xa2, 0x26, 0xfc, 0x70, 0x49, 0x82, 0xa6, 0x89, 0xcd, 0x61, 0x6c, 0x0c, 0xf9, 0x3f, 0xeb, 0xd5,
	0x6f, 0x1b, 0xba, 0xd5, 0x5f, 0x0c, 0xdf, 0x43, 0xdf, 0x98, 0x8d, 0xc7, 0x98, 0xdc, 0x29, 0x3f,
	0xb2, 0x37, 0xac, 0x85, 0x97, 0xd0, 0xdb, 0xc6, 0x8e, 0x23, 0xbe, 0xb7, 0x28, 0xee, 0x98, 0xef,
	0xef, 0x04, 0x6b, 0xe1, 0x3b, 0x98, 0x06, 0xa4, 0xb2, 0x88, 0x7e, 0x92, 0xb6, 0x6a, 0xf1, 0x55,
	0x24, 0x6b, 0xca, 0x71, 0xc0, 0xcd, 0x85, 0x70, 0x87, 0x7c, 0x27, 0x61, 0xd6, 0xc2, 0x8f, 0x70,
	0x71, 0x47, 0xc9, 0xd2, 0xf0, 0x17, 0x27, 0xfc, 0x30, 0x55, 0x77, 0xca, 0x8f, 0x44, 0xc0, 0x5a,
	0xf8, 0x16, 0xce, 0x1a, 0x8f, 0x70, 0xcc, 0xf7, 0x4d, 0x77, 0x91, 0x1f, 0x58, 0xc8, 0x5a, 0x0f,
	0x5d, 0xfd, 0x05, 0x7a, 0xf3, 0x37, 0x00, 0x00, 0xff, 0xff, 0x08, 0xe3, 0x26, 0xaa, 0x91, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LeaderClient is the client API for Leader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LeaderClient interface {
	CreateNewVM(ctx context.Context, in *CreateNewVMRequest, opts ...grpc.CallOption) (*CreateNewVMResponse, error)
	DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error)
	RetrieveStateChanges(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	SendStateUpdate(ctx context.Context, in *StateUpdateRequest, opts ...grpc.CallOption) (*StateUpdateResponse, error)
	MigrateVM(ctx context.Context, in *MigrateVMRequest, opts ...grpc.CallOption) (*MigrateVMResponse, error)
}

type leaderClient struct {
	cc *grpc.ClientConn
}

func NewLeaderClient(cc *grpc.ClientConn) LeaderClient {
	return &leaderClient{cc}
}

func (c *leaderClient) CreateNewVM(ctx context.Context, in *CreateNewVMRequest, opts ...grpc.CallOption) (*CreateNewVMResponse, error) {
	out := new(CreateNewVMResponse)
	err := c.cc.Invoke(ctx, "/leader/CreateNewVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderClient) DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error) {
	out := new(DeleteVMResponse)
	err := c.cc.Invoke(ctx, "/leader/DeleteVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderClient) RetrieveStateChanges(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, "/leader/RetrieveStateChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderClient) SendStateUpdate(ctx context.Context, in *StateUpdateRequest, opts ...grpc.CallOption) (*StateUpdateResponse, error) {
	out := new(StateUpdateResponse)
	err := c.cc.Invoke(ctx, "/leader/SendStateUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderClient) MigrateVM(ctx context.Context, in *MigrateVMRequest, opts ...grpc.CallOption) (*MigrateVMResponse, error) {
	out := new(MigrateVMResponse)
	err := c.cc.Invoke(ctx, "/leader/MigrateVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderServer is the server API for Leader service.
type LeaderServer interface {
	CreateNewVM(context.Context, *CreateNewVMRequest) (*CreateNewVMResponse, error)
	DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error)
	RetrieveStateChanges(context.Context, *StateRequest) (*StateResponse, error)
	SendStateUpdate(context.Context, *StateUpdateRequest) (*StateUpdateResponse, error)
	MigrateVM(context.Context, *MigrateVMRequest) (*MigrateVMResponse, error)
}

// UnimplementedLeaderServer can be embedded to have forward compatible implementations.
type UnimplementedLeaderServer struct {
}

func (*UnimplementedLeaderServer) CreateNewVM(ctx context.Context, req *CreateNewVMRequest) (*CreateNewVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewVM not implemented")
}
func (*UnimplementedLeaderServer) DeleteVM(ctx context.Context, req *DeleteVMRequest) (*DeleteVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVM not implemented")
}
func (*UnimplementedLeaderServer) RetrieveStateChanges(ctx context.Context, req *StateRequest) (*StateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveStateChanges not implemented")
}
func (*UnimplementedLeaderServer) SendStateUpdate(ctx context.Context, req *StateUpdateRequest) (*StateUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendStateUpdate not implemented")
}
func (*UnimplementedLeaderServer) MigrateVM(ctx context.Context, req *MigrateVMRequest) (*MigrateVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateVM not implemented")
}

func RegisterLeaderServer(s *grpc.Server, srv LeaderServer) {
	s.RegisterService(&_Leader_serviceDesc, srv)
}

func _Leader_CreateNewVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServer).CreateNewVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leader/CreateNewVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServer).CreateNewVM(ctx, req.(*CreateNewVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Leader_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leader/DeleteVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServer).DeleteVM(ctx, req.(*DeleteVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Leader_RetrieveStateChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServer).RetrieveStateChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leader/RetrieveStateChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServer).RetrieveStateChanges(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Leader_SendStateUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServer).SendStateUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leader/SendStateUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServer).SendStateUpdate(ctx, req.(*StateUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Leader_MigrateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderServer).MigrateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leader/MigrateVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderServer).MigrateVM(ctx, req.(*MigrateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Leader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "leader",
	HandlerType: (*LeaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewVM",
			Handler:    _Leader_CreateNewVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _Leader_DeleteVM_Handler,
		},
		{
			MethodName: "RetrieveStateChanges",
			Handler:    _Leader_RetrieveStateChanges_Handler,
		},
		{
			MethodName: "SendStateUpdate",
			Handler:    _Leader_SendStateUpdate_Handler,
		},
		{
			MethodName: "MigrateVM",
			Handler:    _Leader_MigrateVM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leader.proto",
}
